### ISSUE TITLE
Unauthorized when trying to create an account

### ISSUE THREAD

**Issue by egg8849** [RodrigoBertotti/firebase-cloud-functions-typescript-example#1]
Hi Rodrigo 👋 first of all - thanks a lot for this template, I think it's greatly structured and will definitely be leveraging it to setup the backend of the project I'm starting now!

I came across a small issue, when following the ["Using postman to test it"](https://github.com/RodrigoBertotti/firebase-cloud-functions-typescript-example?tab=readme-ov-file#using-postman-to-test-it) instructions I was unable to create an account using the `1. Create Account` post request -- the error I'm getting is:
```
<html>

<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8">
	<title>401 Unauthorized</title>
</head>

<body text=#000000 bgcolor=#ffffff>
	<h1>Error: Unauthorized</h1>
	<h2>Your client does not have permission to the requested URL <code>/api/account</code>.</h2>
	<h2></h2>
</body>

</html>
```

I think it's related to the fact that post request requires an `idToken` but my understanding was we were going to create an account in order to get an `idToken` to use it for the subsequent requests

I tried manually creating a username/password user in the firebase console and then using the `2. Login on Google APIS`, that worked and I was able to get an `idToken` but when trying to use that `idToken` to create a "storeOwner" type user in `1. Create Account` I'm still getting the same error

Would really appreciate some guidance here.

Thanks,
-Emilio

**Comment by RodrigoBertotti** [comment]
Hello Emilio, thank you so much, I really appreciate

After reading your issue, I've created a new Firebase project and I decided to run the `firebase deploy --debug` command, I got the same problem you described on Postman

I've noticed that the cloud functions got an error in the deployment, I saw this log from Firebase:

> HTTP Error: 400, Validation failed for trigger projects/testingfirebasejun24/locations/nam5/triggers/onproductupdated-397604: Invalid resource state for \"\": Permission denied while using the Eventarc Service Agent. If you recently started to use Eventarc, it may take a few minutes before all necessary permissions are propagated to the Service Agent. Otherwise, verify that it has Eventarc Service Agent role.
    
The problem was fixed after waiting a little bit and running `firebase deploy` again
